# Generated by Django 3.0.6 on 2020-06-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('catname', models.CharField(default='-', max_length=100)),
                ('catid', models.IntegerField(default='-')),
            ],
        ),
    ]
