# Generated by Django 3.0.6 on 2020-10-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='catid',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='catname',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
