# Generated by Django 3.0.6 on 2020-06-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='ocatid',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='catid',
            field=models.IntegerField(default='0'),
        ),
    ]
