# Generated by Django 3.0.6 on 2020-06-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory', '0002_auto_20200616_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='ocatid',
        ),
    ]
