# Generated by Django 3.0.6 on 2020-06-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('headline', models.TextField()),
                ('description', models.CharField(default='-', max_length=30)),
                ('date', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=30)),
                ('pic', models.CharField(max_length=30)),
            ],
        ),
    ]
