# Generated by Django 3.0.6 on 2020-06-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200610_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='category',
            new_name='categoryname',
        ),
        migrations.AddField(
            model_name='news',
            name='categoryid',
            field=models.IntegerField(default='0'),
        ),
    ]
