# Generated by Django 3.0.6 on 2020-06-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200615_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='decription',
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(default='-'),
        ),
    ]
