# Generated by Django 3.0.6 on 2020-07-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_news_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.TextField(default=''),
        ),
    ]
