# Generated by Django 3.0.6 on 2020-06-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='count',
        ),
    ]
